FROM node:10.13-alpine as builder

# Environment

WORKDIR /home/app
ENV NODE_ENV=production

# Dependencies

COPY package.json /home/app/
# COPY package-lock.json /home/app/
COPY lerna.json /home/app/

COPY packages/bob/package.json /home/app/packages/bob/
COPY packages/bob/package-lock.json /home/app/packages/bob/

COPY packages/common/package.json /home/app/packages/common/
COPY packages/common/package-lock.json /home/app/packages/common/

RUN yarn install
# We should to intall lerna before  
# RUN lerna bootstrap --hoist --ignore-scripts -- --production --no-optional

# Build

COPY . /home/app/
RUN cd packages/bob && yarn build

# Serve

FROM nginx:1.15-alpine
COPY --from=builder /home/app/packages/bob/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
